name: CI/CD Pipeline

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DB_CONNECTION: mysql
      DB_HOST: localhost
      DB_PORT: 3306
      DB_DATABASE: test
      DB_USER: root
      DB_PASSWORD: 1854

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Start MySQL
        run: |
          sudo systemctl start mysql
          mysql -e "CREATE DATABASE IF NOT EXISTS $DB_DATABASE;" -u$DB_USER -p$DB_PASSWORD

      - name: Set up Node.js
        uses: actions/setup-node@v2

        with:
          node-version: "22"

      - name: Install dependencies
        run: npm install

      - name: Run gerar dist
        run: npx tsc

      - name: Run starts
        run: npm run start
